root = "." 
tmp_dir = "tmp"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "templ generate && go build -o ./tmp/app/cmd ./cmd"
# Binary file yields from `cmd`.
bin = "tmp/app"

# Customize binary.
# This is how you start to run your application. Since my application will works like CLI, so to run it, like to make a CLI call.
full_bin = "./tmp/app/cmd"
# This log file places in your tmp_dir.
log = "air_errors.log"
# Watch these filename extensions.
include_ext = ["go", "yaml", "templ", "toml"]
# Ignore these filename extensions or directories.
exclude_dir = ["tmp"]
exclude_regex = ["_templ.go"]
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 1000 # ms

[log]
# Show log time
time = true

[misc]
# Delete tmp directory on exit
clean_on_exit = true
